### ISSUE TITLE
Example Post Component

### ISSUE THREAD

**Issue by danpalmer** [454de6e/gatsby-plugin-blog#1]
I'm looking at using this plugin, but can't figure out how to write a Post component that makes the right queries. My current Post component (below) fails with a load of errors.

```js
const Post = (path, context) => <h1>{path}</h1>;
export default Post;
```

**Comment by rweng** [comment]
I'm also just testing gatsby and this plugin. I have the following Template right now:

```jsx
import React from 'react'
import Paper from '@material-ui/core/Paper';
import Grid from '@material-ui/core/Grid';
import Layout from './layout'
import { Typography } from '@material-ui/core';


const PostTemplate = ({ data }) => {
  const post = data.markdownRemark

  return (
    <div>
      <Layout>
        <Grid container justify='center' alignItems='center'>
          <Grid item xs={10}>
            <Paper>

              <Typography variant='h5' component='h1'>
                {post.frontmatter.title}
              </Typography>

              <div dangerouslySetInnerHTML={{ __html: post.html }} />>
            </Paper>
          </Grid>
        </Grid>
      </Layout>
    </div>
  )
}

export default PostTemplate

export const query = graphql`
  query($path: String!) {
    markdownRemark(fields: { path: { eq: $path } }) {
      html
      frontmatter {
        title
      }
    }
  }
`
```

I installed the plugin and debugged the `gatsby-node.js` to see how everything works. Also, check out the [gatsby tutorial on how pages are created](https://www.gatsbyjs.org/tutorial/part-seven/#creating-pages). Hope that helps.

**Comment by 454de6e** [comment]
You need to look at `gatsby-node.js`. `onCreateNode` processes nodes of type `MarkdownRemark` and infers the date and path from the file name and adds them as fields `date` and `path`. `createPages` then determines the next and previous posts and puts them in the context. Which your template needs to read. All this plugin does it put the metadata into place that your template consumes when generating the post page. I will soon share an example project.
